config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'login',to:'sessions#new'
  get 'signup',to:'sessions#signup'
  post 'signup',to:'sessions#create_user'
  post 'login',to:'sessions#create'
  delete 'logout',to:'sessions#destroy'
  resources :books
  get '/books/filter/:category',to:'books#filter',as:"filter"
  get 'profile/:id',to:'pages#profile',as:'profile'
  get 'profile/:id/edit',to:'pages#edit',as:"profileEdit"
  patch 'profile/:id',to:'pages#update'
  get 'cart/:id',to:'pages#cart',as:'cart'
  post 'books/:id',to:'pages#add_cart'
  get 'about',to:'pages#about'
  delete 'item/:id',to:'carts#destroy',as:"item"
  delete 'profile/:id',to:'users#destroy'
  resources :payments
  get 'search',to:'books#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to:user
    has_one_attached :image
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to:user
    belongs_to:book
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_one_attached:image
    has_many:books
    has_many:carts,dependent: :destroy
    validates :username,presence:true,uniqueness: { case_sensitive: false }
    validates :email,presence:true,uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user,:loggedIn?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def loggedIn?
        !!current_user
    end

    def reqiure_user
        if !loggedIn?
            flash[:success] = "You Must LogIn 🥲!!!"
            redirect_to root_path
        end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :reqiure_user
  def index
    @books = Book.all
  end

  def new
      
  end

  def create
    # byebug
    @book = current_user.books.build(params.require(:book).permit(:title,:author_name,:description,:category,:price,:quantity,:image))
    if @book.save
      flash[:success] = "Your Book is Added 🎆"
      redirect_to books_path
    else
      flash.now[:danger] = "SomeThink Went Wrong 🥲"
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    # byebug
    @book = Book.find(params[:id])
    if @book.update(params.require(:book).permit(:title,:author_name,:description,:category,:price,:quantity,:image))
      flash[:success] = "Updated Successfully 😉!!!"
      redirect_to books_path
    else
      flash.now[:danger] = "SomeThink Went Wrong 🥲"
      render 'edit'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def filter
    @books = Book.where(category: params[:category])
  end

  def search
    # byebug
    @books = Book.where("title LIKE ?","%#{params[:search]}%")
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :reqiure_user
    def destroy
        @cart = Cart.find(params[:id])
        if @cart.destroy
            flash[:success] = "Removed Successfully 🥲!!!"
            redirect_to cart_path(current_user.id)
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :reqiure_user,only:[:profile,:edit,:update,:cart,:add_cart]
  before_action :require_same_user,only:[:profile,:edit,:update,:cart,:add_cart]
  def home

  end
  def profile
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    # byebug
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:username,:email,:password,:image))
      flash[:success] = "Your Account Updated Successfully 😎!!!"
      redirect_to profile_path
    else
      flash.now[:danger] = "SomeThink Went Wrong 🥲"
      render 'edit'
    end
  end
  def cart
    @items = current_user.carts
    @total = 0
  end
  def add_cart
    @product = current_user.carts.build(book_id:params[:id])
    if @product.save
      redirect_to cart_path(current_user.id)
    end
  end
  def about

  end


  private

  def require_same_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      flash[:danger] = "You Have No Access For It !!!"
      redirect_to books_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :reqiure_user,only:[:destroy]
  before_action :require_loggedIn?,only:[:new,:create_user,:create]
  def new

  end
  def signup

  end
  def create_user
    # byebug
    @user = User.new(params.require(:user).permit(:username,:email,:password,:image))
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Your Account was Created Successfully 😁!!! "
      redirect_to books_path
    else
      flash.now[:danger] = "SomeThink Went Wrong 🥲"
      render 'signup'
    end
  end
  def create
    # byebug
    @user = User.find_by(email:params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:success] = "Logged In Successfully 🤠!!! "
      redirect_to books_path
    else
      flash[:danger] = "Invalid Credentials 😢!!!"
      render 'new'
    end
  end
  def destroy
    # byebug
    session[:user_id] = nil
    flash[:success] = "You Logged Successfully 🥺!!!"
    redirect_to login_path
  end


  private

  def require_loggedIn?
    if loggedIn?
      flash[:danger] = "You Are Already Logged In 🤠!!!"
      redirect_to books_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :reqiure_user
    def destroy
        # byebug
        @user = User.find(params[:id])
        if @user.destroy
            session[:user_id] = nil
            flash[:success] = "Account Deleted 🥺!!!"
            redirect_to login_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/books/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="upload-container">
        <div class="upload-content">
          <h2 class="text-center mb-4">Upload Book Details</h2>
          <%= form_with model:@book,method: :put,local:true do |f| %>
            <div class="form-group mt-3">
              <%= f.label :title %>
              <%= f.text_field :title,class:"form-control",placeholder:"Enter book title" %>
            </div>
            <div class="form-group mt-3">
              <%= f.label :author_name %>
              <%= f.text_field :author_name,class:"form-control",placeholder:"Enter author name" %>
            </div>
            <div class="form-group mt-3">
              <%= f.label :description %>
              <%= f.text_area :description,class:"form-control",rows:3,placeholder:"Enter book description" %>
            </div>
             <div class="form-group mt-3">
              <%= f.label :category %>
              <%= f.text_field :category,class:"form-control",placeholder:"Enter book category" %>
            </div>
             <div class="form-group mt-3">
              <%= f.label :price %>
              <%= f.text_field :price,class:"form-control",placeholder:"Enter book price" %>
            </div>
             <div class="form-group mt-3">
              <%= f.label :quantity %>
              <%= f.text_field :quantity,class:"form-control",placeholder:"Enter book quantity" %>
            </div>
            <div class="form-group mt-3">
              <%= f.label :image %>
              <%= f.file_field :image,class:"form-control" %>
            </div><br>
            <%= f.submit "Upload",class:"btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/filter.html.erb
<div class="container mt-5">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="card">
          <%= link_to book_path(book.id) do %>
            <%= image_tag(book.image, class: "card-img-top") if book.image.attached? %>
            <div class="card-body">
              <h5 class="card-title"><%= book.title %></h5>
              <p class="card-text"><%= truncate(book.description, length: 20) %></p>
            </div>
          <% end %>
          <div class="card-footer">
            <%= link_to "Buy Now", book_path(book), method: :post, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-5">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="card">
          <%= link_to book_path(book.id) do %>
            <%= image_tag(book.image, class: "card-img-top") if book.image.attached? %>
            <div class="card-body">
              <h5 class="card-title"><%= book.title %></h5>
              <p class="card-text"><%= truncate(book.description, length: 20) %></p>
            </div>
          <% end %>
          <div class="card-footer">
            <%= link_to "Buy Now", book_path(book), method: :post, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="upload-container">
        <div class="upload-content">
          <h2 class="text-center mb-4">Upload Book Details</h2>
          <%= form_with scope: :book,url:"/books",local:true do |f| %>
            <div class="form-group mt-3">
              <%= f.label :title %>
              <%= f.text_field :title,class:"form-control",placeholder:"Enter book title" %>
            </div>
            <div class="form-group mt-3">
              <%= f.label :author_name %>
              <%= f.text_field :author_name,class:"form-control",placeholder:"Enter author name" %>
            </div>
            <div class="form-group mt-3">
              <%= f.label :description %>
              <%= f.text_area :description,class:"form-control",rows:3,placeholder:"Enter book description" %>
            </div>
             <div class="form-group mt-3">
              <%= f.label :category %>
              <%= f.text_field :category,class:"form-control",placeholder:"Enter book category" %>
            </div>
             <div class="form-group mt-3">
              <%= f.label :price %>
              <%= f.text_field :price,class:"form-control",placeholder:"Enter book price" %>
            </div>
             <div class="form-group mt-3">
              <%= f.label :quantity %>
              <%= f.text_field :quantity,class:"form-control",placeholder:"Enter book quantity" %>
            </div>
            <div class="form-group mt-3">
              <%= f.label :image %>
              <%= f.file_field :image,class:"form-control" %>
            </div><br>
            <%= f.submit "Upload",class:"btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<div class="container mt-5">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-lg-3 col-md-4 col-sm-6">
        <div class="card">
          <%= link_to book_path(book.id) do %>
            <%= image_tag(book.image, class: "card-img-top") if book.image.attached? %>
            <div class="card-body">
              <h5 class="card-title"><%= book.title %></h5>
              <p class="card-text"><%= truncate(book.description, length: 20) %></p>
            </div>
          <% end %>
          <div class="card-footer">
            <%= link_to "Buy Now", book_path(book), method: :post, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="item-container">
        <div class="row">
          <div class="col-md-6">
            <%= image_tag(@book.image ,class:"item-image") if @book.image.attached? %>
          </div>
          <div class="col-md-6 item-description">
            <h2><%= @book.title %></h2>
            <p><%= truncate(@book.description,length:150) %></p>
            <p class="item-price">$<%= @book.price %></p>
            <%= link_to "Add To Cart",'/books/'+@book.id.to_s,method: :post,class:"btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container-fluid">
    <%= link_to "Book Store",root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Home",root_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About",about_path,class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Books",books_path,class:"nav-link" %>
        </li>
        <% if loggedIn? %>
        <li class="nav-item">
          <%= link_to "Carts",cart_path(current_user.id),class:"nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
    <% if loggedIn? %>
    <div class="container d-flex justify-content-end">
      <%= form_tag search_path,method: :get do %>
        <%= text_field_tag :search , params[:search] %>
        <%= button_tag type: :submit do %>
          Search
        <% end %>
      <% end %>
    <div>
    <div class="container">
      <div class="dropdown d-flex justify-content-end">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_user.username %>
        </button>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton"> <!-- Add dropdown-menu-end class -->
          <li><%= link_to "Profile",profile_path(current_user.id),class:"dropdown-item" %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Add Books",new_book_path,class:"dropdown-item" %></li>
          <% end %>
          <%= link_to "Carts",cart_path(current_user.id),class:"dropdown-item" %>
          <li><%= link_to "Logout",logout_path,method: :delete,class:"dropdown-item" %></li>
        </ul>
      </div>
    </div>
  </div>
  <% else %>
  <div class="container">
  <div class="dropdown d-flex justify-content-end">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
      Account
    </button>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton"> <!-- Add dropdown-menu-end class -->
      <li><%= link_to "Log In",login_path,class:"dropdown-item" %></li>
      <%= link_to "Sign Up",signup_path,class:"dropdown-item" %>
    </ul>
  </div>
</div>
  </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookStoreApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% flash.each do |k,m| %>
      <!-- Success flash message -->
      <div class="alert alert-dismissible alert-<%= k %>">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong><%= m %></strong>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="about-card">
        <h2 class="text-center mb-4">About Our Bookstore</h2>
        <p>Welcome to our bookstore! We are passionate about providing the best selection of books for our customers. Whether you're a bookworm looking for your next favorite novel or a student in need of textbooks, we've got you covered.</p>
        <p>Our bookstore features a wide range of genres, from fiction and non-fiction to mystery and science fiction. We also offer a curated collection of rare and collectible books for enthusiasts.</p>
        <p>At our bookstore, we believe in fostering a love of reading and lifelong learning. Our knowledgeable staff are always on hand to recommend new titles and help you find exactly what you're looking for.</p>
        <p>Thank you for choosing our bookstore. We look forward to serving you and helping you discover your next great read!</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/cart.html.erb
<div class="container mt-5">
    <div class="row">
        <% @items.each do |item| %>
            <div class="col-md-6">
                <div class="cart-item">
                    <div class="row">
                <div class="col-md-4">
                    <%= image_tag(item.book.image, class: "cart-image mx-auto d-block") if item.book.image.attached? %>
                </div>
                <div class="col-md-8-ml-5">
                    <div class="cart-details">
                        <h3><%= item.book.title %></h3>
                        <p>Price: $<%= item.book.price %></p>
                        <%= link_to "Remove",item_path(item.id),method: :delete,class:"btn btn-danger" %>
                    </div>
                    <div><% @total = @total+item.book.price %></div>
                </div>
            </div>
        </div>
        </div>
        <% end %>
    </div>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="buy-section">
        <h2 class="text-center">Buy Section</h2>
        <p class="text-center">Total Price: <%= number_to_currency(@total) %></p>
        <button class="btn btn-primary buy-button">Buy Now</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/edit.html.erb
<div class="signup-container">
  <h2>Edit User</h2>
  <%= form_with model:@user,url:profile_path,method: :patch, local:true do |f| %>
    <div class="form-floating mt-3">
      <%= f.text_field :username,class:"form-control",placeholder:"Username" %>
      <%= f.label :username %>
    </div>
    <div class="form-floating mt-3">
      <%= f.email_field :email,class:"form-control",placeholder:"name@example.com" %>
      <%= f.label :email %>
    </div>
    <div class="form-floating mt-3">
      <%= f.password_field :password,class:"form-control",placeholder:"Password" %>
      <%= f.label :password %>
    </div>
    <%= f.file_field :image,class:"form-control" %></br>
    <%= f.submit "Update User",class:"signup-btn" %>
  <% end %>
</div>

app/views/pages/home.html.erb
    <!-- Jumbotron -->
    <div class="jumbotron">
  <h1 class="display-4">Welcome to Our Book Shop</h1>
  <p class="lead">Discover amazing features and services.</p>
  <%= link_to "Learn More",about_path,class:"btn btn-lg btn-primary" %>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
    <%= link_to filter_path("fiction") do %>
      <div class="feature-box">
        <h3>Fiction Books</h3>
        <p>A work of fiction is created in the imagination of its author. The author invents the story and makes up the characters, the plot or storyline, the dialogue and sometimes even the setting. A fictional work does not claim to tell a true story.</p>
      </div>
      <% end %>
    </div>
    <div class="col-lg-4">
    <%= link_to filter_path("non-fiction") do %>
      <div class="feature-box">
        <h3>Non-Fiction Books</h3>
        <p>Non-fiction (or nonfiction) is any document or media content that attempts, in good faith, to convey information only about the real world, rather than being grounded in imagination. Non-fiction typically aims to present topics objectively based on historical, scientific, and empirical information.</p>
      </div>
      <% end %>
    </div>
    <div class="col-lg-4">
    <%= link_to filter_path("story") do %>
      <div class="feature-box">
        <h3>Story Books</h3>
        <p>A storybook is a book of stories for children. As a child she learned to draw by tracing pictures out of her mother's old storybooks.</p>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="profile-card">
        <div class="profile-image mx-auto">
        <%= image_tag(@user.image, style: "height: 170px;width : 140px") %>
        </div>
        <div class="profile-details text-center">
          <h2><%= @user.username %></h2>
          <p>Email: <%= @user.email %></p>
          <p>Location: Avaraikulam</p>
          <p>Bio: Learning Ruby On Rails</p>
          <%= link_to "Edit Profile",profileEdit_path(@user.id),class:"btn btn-primary" %>
          <%= link_to "Delete Profile",profile_path(@user.id),method: :delete,class:"btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>